language: ruby
rvm:
  - 2.1.3
cache:
  bundler: true
addons:
  code_climate:
    repo_token: 6f0a7c68f914b08ad6763051718160e581c8f4ec4801a603e9f0cd2097edcbae
script:
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database bank_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
after_script:
  - cat lcov.info | codeclimate
